// <auto-generated />
using System;
using FlightAPI.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightAPI.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20230326084704_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightAPI.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VJ001",
                            Note = "Go to Tokyo",
                            Version = "1.0"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VJ002",
                            Note = "Go to Osaka",
                            Version = "1.0"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VJ003",
                            Note = "Go to Kyoto",
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("FlightAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Admin@vietjetair.com",
                            Password = "123456",
                            Phone = "0123456789",
                            RoleName = "ADMIN",
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Staff@vietjetair.com",
                            Password = "123456",
                            Phone = "0123456789",
                            RoleName = "GO",
                            Username = "GO Employee"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Pilot@vietjetair.com",
                            Password = "123456",
                            Phone = "0987654321",
                            RoleName = "PILOT",
                            Username = "Pilot"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Crew@vietjetair.com",
                            Password = "123456",
                            Phone = "0987654321",
                            RoleName = "CREW",
                            Username = "Crew"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
